### ISSUE TITLE
Calculated columns on Join tables don't currently work (due to a cast issues on pullrow()

### ISSUE THREAD

**Issue by chrisjstevo** [finos/vuu#1000]
This should be simple to fix by filtering out calc columns from the initial build step and apply at the end. 

```13:56:09.969 [sessionRunner1] ERROR o.f.toolbox.thread.LifeCycleRunner - [sessionRunner] threw an exception in run
java.lang.ClassCastException: class org.finos.vuu.core.table.CalculatedColumn cannot be cast to class org.finos.vuu.core.table.JoinColumn (org.finos.vuu.core.table.CalculatedColumn and org.finos.vuu.core.table.JoinColumn are in unnamed module of loader 'app')
	at org.finos.vuu.core.table.JoinTable.$anonfun$pullRowAsArray$1(JoinTable.scala:470)
	at scala.collection.immutable.List.map(List.scala:250)
	at org.finos.vuu.core.table.JoinTable.pullRowAsArray(JoinTable.scala:470)
	at org.finos.vuu.net.DefaultMessageHandler.formatOneRowUpdate(ClientConnectionCreator.scala:113)
	at org.finos.vuu.net.DefaultMessageHandler.$anonfun$formatDataOutbound$2(ClientConnectionCreator.scala:91)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
	at org.finos.vuu.net.DefaultMessageHandler.formatDataOutbound(ClientConnectionCreator.scala:91)
	at org.finos.vuu.net.DefaultMessageHandler.sendUpdatesInternal(ClientConnectionCreator.scala:53)
	at org.finos.vuu.net.DefaultMessageHandler.sendUpdates(ClientConnectionCreator.scala:77)
	at org.finos.vuu.net.ClientSessionContainerImpl.$anonfun$runOnce$1(ClientConnectionCreator.scala:234)
	at org.finos.vuu.net.ClientSessionContainerImpl.$anonfun$runOnce$1$adapted(ClientConnectionCreator.scala:234)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at org.finos.vuu.net.ClientSessionContainerImpl.runOnce(ClientConnectionCreator.scala:234)
	at org.finos.vuu.core.VuuServer.$anonfun$handlerRunner$1(VuuServer.scala:64)
	at org.finos.toolbox.thread.Runner$$anon$1.run(Runner.scala:47)
	at java.base/java.lang.Thread.run(Thread.java:840)
13:56:09.969 [sessionRunner1] INFO  o.f.toolbox.thread.LifeCycleRunner - [sessionRunner] is exiting
```

**Comment by chrisjstevo** [comment]
Fixed
