### ISSUE TITLE
Missing FTSE & SP5 constituents

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1052]
### Steps to Reproduce:
 1.  If you create a basket trade using these, you get empty basket trade constituents table. 
 2.  If you open the basket constituents table, they are not loaded

### Environment:
https://kdc4b442841vuu01.aks.azure.ubsdev.net/vuu-latest/index.html

### Additional Context:
Possible issue with the static file copy

**Comment by naleeha** [comment]
13:23:24.863 [BasketConstituentProvider1] INFO  o.f.v.c.m.b.csv.CsvStaticLoader$ - Loading basket static:.FTSE100(/app/resources/static/ftse100.csv)
13:23:24.864 [BasketConstituentProvider1] ERROR o.f.t.thread.RunOnceLifeCycleRunner - [BasketConstituentProvider] threw an exception in run
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
	at scala.collection.mutable.Growable.addAll(Growable.scala:61)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.mutable.ArrayBuilder.addAll(ArrayBuilder.scala:66)
	at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1319)
	at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1313)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1300)
	at org.finos.vuu.core.module.basket.csv.CsvStaticLoader$.loadConstituent(CsvStaticLoader.scala:18)
	at org.finos.vuu.core.module.basket.provider.BasketConstituentProvider.updateBasketConstituents(BasketConstituentProvider.scala:25)
	at org.finos.vuu.core.module.basket.provider.BasketConstituentProvider.$anonfun$runOnce$1(BasketConstituentProvider.scala:21)
	at org.finos.vuu.core.module.basket.provider.BasketConstituentProvider.$anonfun$runOnce$1$adapted(BasketConstituentProvider.scala:21)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
	at org.finos.vuu.core.module.basket.provider.BasketConstituentProvider.runOnce(BasketConstituentProvider.scala:21)
	at org.finos.vuu.core.module.basket.provider.BasketConstituentProvider.$anonfun$runner$1(BasketConstituentProvider.scala:13)
	at org.finos.toolbox.thread.Runner$$anon$1.run(Runner.scala:47)
	at java.base/java.lang.Thread.run(Thread.java:829)
