### ISSUE TITLE
Error and edgecase handling getting ignite data and updating table

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1216]

**Comment by naleeha** [comment]
Example error - when filter input fails on the ui and sends "undefined undefined undefined" to server, currently blows up 


17:58:55.214 [viewPortExecutorRunner[4]7] INFO  o.f.v.e.ignite.IgniteOrderStore - Loaded Ignite ChildOrder for 5156 rows, from index : 0 where  order by 
line 1:10 no viable alternative at input 'undefinedundefined'
17:58:55.255 [nioEventLoopGroup-3-5] ERROR o.f.vuu.viewport.ViewPortContainer - could not parse filter undefined undefined undefined
org.antlr.v4.runtime.misc.ParseCancellationException: null
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
	at org.finos.vuu.grammar.FilterParser.term(FilterParser.java:513)
	at org.finos.vuu.grammar.FilterParser.andExpression(FilterParser.java:221)
	at org.finos.vuu.grammar.FilterParser.orExpression(FilterParser.java:164)
	at org.finos.vuu.grammar.FilterParser.start(FilterParser.java:121)
	at org.finos.vuu.core.filter.FilterSpecParser$.parse(FilterSpecParser.scala:49)
	at org.finos.vuu.viewport.ViewPortContainer.$anonfun$parseFilter$1(ViewPortContainer.scala:406)
	at scala.util.Try$.apply(Try.scala:210)
	at org.finos.vuu.viewport.ViewPortContainer.parseFilter(ViewPortContainer.scala:406)
	at org.finos.vuu.viewport.ViewPortContainer.change(ViewPortContainer.scala:429)
	at org.finos.vuu.core.CoreServerApiHandler.process(CoreServerApiHandler.scala:272)
	at org.finos.vuu.net.DefaultMessageHandler.handle(ClientConnectionCreator.scala:132)
	at org.finos.vuu.net.RequestProcessor.handleViewServerMessage(RequestProcessor.scala:76)
	at org.finos.vuu.net.RequestProcessor.handle(RequestProcessor.scala:43)
	at org.finos.vuu.net.ViewServerHandler.handle(ViewServerHandler.scala:39)
	at org.finos.vuu.net.ws.WebSocketServerHandler.handleWebSocketFrame(WebSocketServerHandler.scala:99)
	at org.finos.vuu.net.ws.WebSocketServerHandler.channelRead0(WebSocketServerHandler.scala:29)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.antlr.v4.runtime.NoViableAltException: null
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:470)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
	at org.finos.vuu.grammar.FilterParser.term(FilterParser.java:387)
	... 46 common frames omitted
17:58:55.255 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - [VP] default else condition in change() call
17:58:55.255 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - changeStructure(..) onlySortOrFilterChange=true
17:58:55.257 [viewPortExecutorRunner[4]7] INFO  o.f.v.e.i.p.IgniteOrderDataProvider - Updated 5156 table rows
line 1:10 no viable alternative at input 'undefinedundefined'
17:58:55.259 [viewPortExecutorRunner[4]7] ERROR o.f.v.p.v.v.VirtualizedViewPortCallable$ - null - [Ljava.lang.StackTraceElement;@3a86902c
Exception in thread "viewPortExecutorRunner[4]7" java.lang.NullPointerException: Cannot invoke "org.finos.vuu.viewport.ViewPort.table()" because the return value of "java.util.concurrent.FutureTask.get()" is null
	at org.finos.vuu.core.VuuServer$$anon$1.newWorkItem(VuuServer.scala:90)
	at org.finos.toolbox.thread.LifeCycleRunOncePerThreadExecutorRunner$$anon$1.newWorkItem(LifeCycleRunOncePerThreadExecutorRunner.scala:46)
	at org.finos.toolbox.thread.LifeCycleRunOncePerThreadExecutorRunner$$anon$1.shouldResubmit(LifeCycleRunOncePerThreadExecutorRunner.scala:44)
	at org.finos.toolbox.thread.executor.ResubmitExecutor.afterExecute(ResubmitExecutor.scala:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1139)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
line 1:10 no viable alternative at input 'undefinedundefined'
17:58:56.503 [nioEventLoopGroup-3-5] ERROR o.f.vuu.viewport.ViewPortContainer - could not parse filter undefined undefined undefined
org.antlr.v4.runtime.misc.ParseCancellationException: null
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
	at org.finos.vuu.grammar.FilterParser.term(FilterParser.java:513)
	at org.finos.vuu.grammar.FilterParser.andExpression(FilterParser.java:221)
	at org.finos.vuu.grammar.FilterParser.orExpression(FilterParser.java:164)
	at org.finos.vuu.grammar.FilterParser.start(FilterParser.java:121)
	at org.finos.vuu.core.filter.FilterSpecParser$.parse(FilterSpecParser.scala:49)
	at org.finos.vuu.viewport.ViewPortContainer.$anonfun$parseFilter$1(ViewPortContainer.scala:406)
	at scala.util.Try$.apply(Try.scala:210)
	at org.finos.vuu.viewport.ViewPortContainer.parseFilter(ViewPortContainer.scala:406)
	at org.finos.vuu.viewport.ViewPortContainer.change(ViewPortContainer.scala:429)
	at org.finos.vuu.core.CoreServerApiHandler.process(CoreServerApiHandler.scala:272)
	at org.finos.vuu.net.DefaultMessageHandler.handle(ClientConnectionCreator.scala:132)
	at org.finos.vuu.net.RequestProcessor.handleViewServerMessage(RequestProcessor.scala:76)
	at org.finos.vuu.net.RequestProcessor.handle(RequestProcessor.scala:43)
	at org.finos.vuu.net.ViewServerHandler.handle(ViewServerHandler.scala:39)
	at org.finos.vuu.net.ws.WebSocketServerHandler.handleWebSocketFrame(WebSocketServerHandler.scala:99)
	at org.finos.vuu.net.ws.WebSocketServerHandler.channelRead0(WebSocketServerHandler.scala:29)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.antlr.v4.runtime.NoViableAltException: null
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:470)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
	at org.finos.vuu.grammar.FilterParser.term(FilterParser.java:387)
	... 46 common frames omitted
17:58:56.503 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - [VP] default else condition in change() call
17:58:56.503 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - changeStructure(..) onlySortOrFilterChange=true
17:58:59.195 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - [VP] default else condition in change() call
17:58:59.195 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - changeStructure(..) onlySortOrFilterChange=true
17:59:01.143 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - Sending updates on 210 inrangeKeys
17:59:01.143 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - VP Change Range [nha1-VP-00000006] 90->366, was 0->156, took: 1 millis
17:59:01.224 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - Sending updates on 276 inrangeKeys
17:59:01.224 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - VP Change Range [nha1-VP-00000006] 3625->3901, was 90->366, took: 1 millis
17:59:01.315 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - Sending updates on 276 inrangeKeys
17:59:01.315 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - VP Change Range [nha1-VP-00000006] 16996->17272, was 3625->3901, took: 1 millis
17:59:01.396 [nioEventLoopGroup-3-5] INFO  org.finos.vuu.viewport.ViewPortImpl - Sending updates on 276 inrangeKeys
17:59:01.396 [nioEventLoopGroup-3-5] INFO  o.f.vuu.viewport.ViewPortContainer - VP Change Range [nha1-VP-00000006] 17381->17657, was 16996->17272, took: 1 millis
17:59:06.418 [nioEventLoopGroup-3-5] INFO  o.f.vuu.core.CoreServerApiHandler - HB [20]
17:59:11.442 [nioEventLoopGroup-3-5] INFO  o.f.vuu.core.CoreServerApiHandler - HB [21]
17:59:16.465 [nioEventLoopGroup-3-5] INFO  o.f.vuu.core.CoreServerApiHandler - HB [20]
17:59:21.488 [nioEventLoopGroup-3-5] INFO  o.f.vuu.core.CoreServerApiHandler - HB [21]
